import { BellRing, Box, CalendarClock, Check, ChevronRight, Clipboard, Download, ExternalLink, Eye, EyeOff, FileCode2, FilePlus2, LayoutDashboard, LogOut, MessageCircle, Package, Plus, Power, RefreshCw, Search, Send, Settings2, Store as StoreIcon, Trash2, Users, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import BrandLogo from '../components/BrandLogo';
import HtmlEditor from '../components/HtmlEditor';
import Modal from '../components/Modal';
import { useAuth } from '../contexts/AuthContext';
import { apiFetch, storeDomain, storeLink, uploadImage } from '../lib/api';
import type { Application, DashboardData, Store } from '../types';
import '../html-storefront.css';

const daysLeft = (store: Store) => {
  if (!store.is_active) return { label: 'OFF', tone: 'off' };
  const orders = Number(store.orders_this_period || 0);
  if (store.upkeep_plan === 'PRO') return { label: `PRO · ${orders} orders · KES 999`, tone: 'paid' };
  return { label: `FREE · ${orders}/7 orders`, tone: 'active' };
};

const CLIENT_STORE_PROMPT = `Design one extraordinary, completely original storefront for this client.

STORE NAME: [FILL IN]
LOCATION: [FILL IN]
WHAT THEY SELL: [FILL IN]
PRODUCT CATEGORIES: [FILL IN]
TARGET CUSTOMER: [FILL IN]
BRAND PERSONALITY: [FILL IN]
PREFERRED COLOURS: [FILL IN OR WRITE "SURPRISE ME"]
CONTACT DETAILS: [FILL IN]
SPECIAL STORY, OFFER OR TRUST POINTS: [FILL IN]

You are the creative director of a world-class, million-dollar design team. Create the absolute best visual storefront this business could possibly have: unforgettable, premium, artistic, highly polished, mobile-first and unmistakably designed for this exact client. Never use a generic ecommerce template. Build a unique art direction, typography system, colour palette, imagery style, spacing rhythm and responsive composition that makes the business look established, desirable and exceptional.

Push the work far beyond an ordinary website. The home hero must be the strongest and most impressive part of the entire store: breathtaking, distinctive, immediately clear and perfectly matched to the store's products, location, story and audience. Every detail should feel intentional, expensive and custom-made, as though an elite agency spent months creating it. The finished storefront must be absolutely perfect, amazing to look at, completely unique and deeply tailored to this specific store.

STRUCTURE AND DESIGN RULES:
- Return one complete, self-contained HTML document only, with all CSS inside a <style> tag. Do not include any <script> tag, JavaScript, framework, build tool or click handler.
- OUTPUT RULE (mandatory): the entire storefront — every section, every style rule, every piece of copy, every icon and every colour — must exist inside this single index.html file. Nothing may be split into a separate .css file, .js file, image folder, font file or any other external asset the platform would need to host separately. If it isn't real, permanently-hosted content (per the IMAGE RULE below), it must be written directly inside this one HTML document so the file is complete and self-sufficient on its own, ready to copy and paste as one file.
- Use the real store details supplied above. Do not use placeholder tokens.
- Put every important brand colour directly into dependable plain CSS using hex, rgb, hsl, gradients or CSS variables. Do not rely on framework configuration, JavaScript-generated colours, external icon libraries or runtime class generation. This keeps the intended palette stable wherever the storefront is opened.
- Any decorative emoji must be written directly as a Unicode character in the HTML, never generated by JavaScript. Pair important emoji with readable text and prefer clean inline SVG or CSS shapes when an icon must render consistently.
- IMAGE RULE (mandatory): Every <img> src (and every CSS background-image url()) must be a real, permanent, already-hosted URL — a direct Unsplash image link or another live image CDN URL — that will actually resolve when the page loads. Do not reference a local or relative file path (e.g. /images/hero.jpg, ./assets/photo.png, hero-jersey.jpg) unless that exact file is confirmed to already exist in the site's hosted images folder; an invented path to a file that doesn't exist will render as a broken image icon. Do not embed images as base64 data URIs (e.g. data:image/jpeg;base64,...) anywhere in the document — even though these avoid broken-image icons, each embedded image inflates as text by roughly a third, bloats the HTML file size, slows page load, and prevents the browser from caching images separately from the page. If no real hosted image is available for a given spot, omit the image entirely (use a solid colour, gradient or CSS-drawn shape instead) rather than fabricating a fake path or inlining base64 data.
- Do not include any WhatsApp chat button, floating WhatsApp icon, wa.me link, WhatsApp navigation item or general WhatsApp contact link anywhere. The only WhatsApp destination is created privately by the StoYangu app after a shopper confirms a real product order.
- The sticky navigation must always remain visible while scrolling.
- The navigation must show exactly three links: Home, Products, Contact.
- Never add a hamburger, three-line menu, hidden mobile drawer, shop button, cart button or any fourth navigation item. The three links must remain clearly visible on phones and desktops.
- NAVBAR LAYOUT (mandatory, applies to every store): the store logo sits on the top left of the navbar, sized big enough to visually span two stacked lines of content beside it. MOBILE: directly beside the logo, stack two lines — the store name written out in full on the top line (never truncated, clipped, shrunk to illegibility or cut with an ellipsis — let it wrap or use a fluid/responsive font-size so the whole name always reads cleanly), and the Home, Products, Contact links arranged neatly underneath it on the second line. Style this name-then-links stack with deliberate, polished spacing (not a cramped default) so the logo, the full store name and the nav links read as one cohesive, high-class unit rather than competing for the same row. Never let the store name overlap, crowd or push against the nav links — the two-line stack next to the logo exists specifically to prevent that. DESKTOP: rearrange the navbar into one balanced row — the logo on the LEFT, the Home / Products / Contact menu buttons centered in the MIDDLE, and the full store name on the RIGHT — with polished spacing so nothing overlaps or looks cramped.
- HOME: create a spectacular hero as the visual centrepiece — the hero may be a maximum of 2 sections (one main hero plus at most one supporting trust/story block), never more — followed by strong trust, story or lifestyle content that fits the client.
- PRODUCTS: fully design the section background, heading, spacing, category-filter area, responsive product grid, product-card appearance and an excellent "View Product" button style. Leave <div id="filters" data-category-filters></div> for category buttons and <div id="productGrid" data-product-grid></div> for live products. Also include a hidden <template id="stoyangu-card-template"> containing one beautifully designed <article class="product-card"> with an image, .product-category, .product-name, .product-price and a <button type="button" data-view-product>View Product</button>. The app clones that exact design and fills it with real products and categories. Your CSS must make .filter-chip, .product-card and [data-view-product] look exceptional.
- You may add any additional decorative or storytelling sections the store needs BETWEEN the PRODUCTS and CONTACT sections to make the store feel richer, but they must not appear in the navigation.
- CONTACT: create a clear, beautiful contact section using the real details supplied above.
- Finish with a premium, fully designed footer that feels consistent with the store. It may show the store name, location, opening information, normal telephone text or a tel: call link, email and tasteful social links, but it must not include a WhatsApp or wa.me link.
- Do not create product data, category names, carts, checkout flows or interaction JavaScript. The app supplies the live product cards and their behaviour.
- Product cards must have only one customer action, labelled exactly "View Product".
- RESPONSIBILITY BOUNDARY: your HTML controls every visual detail up to and including the product card and the appearance of its View Product button. Your work ends at that button. Do not give the button an href, onclick, modal target or custom behaviour. It must be exactly <button type="button" data-view-product>View Product</button>. When it is clicked, the StoYangu app takes over and immediately opens the universal product details experience.
- Do not draw, describe, style or implement anything that happens after View Product is clicked. Do not include a product-details overlay, popup markup, hidden modal, phone step, delivery form or ordering elements anywhere in the HTML.
- Keep the <template id="stoyangu-card-template"> separate from the visible product grid. Include exactly one template card; do not hard-code sample products into the visible page.
- Use complete, persuasive copy tailored to the client. Do not include lorem ipsum, TODOs, build notes or explanations outside the final HTML.`;

export default function FounderDashboard() {
  const { signOut } = useAuth();
  const navigate = useNavigate();
  const [data, setData] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [clientPromptCopied, setClientPromptCopied] = useState(false);
  const [search, setSearch] = useState(''); const [newStore, setNewStore] = useState(false); const [editStore, setEditStore] = useState<Store | null>(null); const [jsonStore, setJsonStore] = useState<Store | null>(null); const [notifications, setNotifications] = useState(false); const [deletingStore, setDeletingStore] = useState<Store | null>(null); const [archiveView, setArchiveView] = useState<{ store: Store; archives: Array<{ id: number; order_count: number; archived_at: string; store_name: string; orders: Array<Record<string, unknown>> }> } | null>(null);
  const load = useCallback(async () => { setError(''); try { setData(await apiFetch<DashboardData>('/api/dashboard')); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load dashboard.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    let timer = 0;
    const generate = () => apiFetch('/api/notifications?action=generate').catch((reason) => console.warn('Daily review generation will retry when opened:', reason));
    const now = new Date();
    const sevenPmKenya = new Date(now); sevenPmKenya.setUTCHours(16, 0, 0, 0);
    if (now >= sevenPmKenya) {
      generate();
      sevenPmKenya.setUTCDate(sevenPmKenya.getUTCDate() + 1);
    }
    timer = window.setTimeout(() => { generate(); }, Math.max(1000, sevenPmKenya.getTime() - Date.now()));
    return () => window.clearTimeout(timer);
  }, []);
  const stores = useMemo(() => (data?.stores || []).filter((store) => `${store.name} ${store.whatsapp} ${store.slug}`.toLowerCase().includes(search.toLowerCase())), [data, search]);
  const downloadArchivedOrders = (store: Store, orders: Array<Record<string, unknown>>) => {
    if (!orders?.length) return;
    const header = 'Order key,Product,Price (KES),Customer phone,Colour,Size,Fulfilment,Note,Status,Created at';
    const csv = [header, ...orders.map((order) => [order.order_key, order.product_name, order.product_price, order.customer_phone, order.color, order.size, order.fulfilment, String(order.note || '').replace(/\s+/g, ' '), order.status, order.created_at].map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(','))].join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const anchor = document.createElement('a');
    anchor.href = url; anchor.download = `${store.slug}-archived-orders.csv`; anchor.click();
    URL.revokeObjectURL(url);
  };
  const toggle = async (store: Store) => {
    try {
      if (store.is_active) {
        const confirmed = window.confirm(`Turn OFF ${store.name}?\n\nAll of its orders will be saved safely to the archive and removed from the live store, and its latest update will be cleared. You can view or download those orders any time from the archive button, and restore them when you turn the store back on.`);
        if (!confirmed) return;
        await apiFetch('/api/stores', { method: 'PUT', body: JSON.stringify({ action: 'billing', id: store.id, is_active: false }) });
        await load();
        return;
      }
      const archives = await apiFetch('/api/stores', { method: 'PUT', body: JSON.stringify({ action: 'archived-orders', id: store.id }) }) as Array<{ order_count: number }>;
      let restore = false;
      const latest = archives?.[0];
      if (latest?.order_count) {
        restore = window.confirm(`${store.name} has ${latest.order_count} saved orders from when it was turned off.\n\nOK = restore those orders to the store now.\nCancel = start blank (the saved orders stay archived and you can view them any time).`);
      }
      await apiFetch('/api/stores', { method: 'PUT', body: JSON.stringify({ action: 'billing', id: store.id, is_active: true, restore_orders: restore }) });
      await load();
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not update store.'); }
  };
  const openArchives = async (store: Store) => {
    try {
      const archives = await apiFetch('/api/stores', { method: 'PUT', body: JSON.stringify({ action: 'archived-orders', id: store.id }) }) as Array<{ id: number; order_count: number; archived_at: string; store_name: string; orders: Array<Record<string, unknown>> }>;
      setArchiveView({ store, archives: archives || [] });
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not load archived orders.'); }
  };
  const applicationStatus = async (application: Application, status: Application['status']) => { await apiFetch('/api/applications', { method: 'PUT', body: JSON.stringify({ id: application.id, status }) }); await load(); };
  const handleSignOut = async () => { await signOut(); navigate('/login', { replace: true }); };
  const copyClientPrompt = async () => { try { await navigator.clipboard.writeText(CLIENT_STORE_PROMPT); setClientPromptCopied(true); window.setTimeout(() => setClientPromptCopied(false), 2200); } catch { window.prompt('Copy this AI prompt manually:', CLIENT_STORE_PROMPT); } };
  return <div className="dashboard-shell"><aside className="dashboard-sidebar"><BrandLogo /><div className="founder-chip"><span>F</span><div><strong>Founder</strong><small>Shared workspace</small></div></div><nav><a className="active" href="#overview"><LayoutDashboard /> Overview</a><a href="#applications"><FilePlus2 /> Applications</a><a href="#stores"><StoreIcon /> All stores</a><button onClick={() => setNotifications(true)}><BellRing /> Notifications</button><button onClick={copyClientPrompt}><Clipboard /> Client AI prompt</button></nav><button className="sidebar-signout" onClick={handleSignOut}><Settings2 /> Sign out</button></aside><main className="dashboard-main"><div className="mobile-topbar"><BrandLogo /><div className="mobile-topbar-actions"><button onClick={() => setNotifications(true)}><BellRing /> Alerts</button><button onClick={handleSignOut}><LogOut /> Sign out</button></div></div><header className="dashboard-top"><div><span className="eyebrow">Founder dashboard</span><h1>StoYangu overview</h1><p>Everything moving across the platform today.</p></div><div className="top-actions"><button className="secondary-button source-download update-pack-button" onClick={copyClientPrompt}>{clientPromptCopied ? <><Check /> Prompt copied!</> : <><Clipboard /> Copy new-client AI prompt</>}</button><button className="secondary-button" onClick={() => setNotifications(true)}><BellRing /> Notifications</button><button className="button-primary compact" onClick={() => setNewStore(true)}><Plus /> New store</button></div></header>
    {error && <div className="dashboard-error">{error}<button onClick={load}><RefreshCw /> Try again</button></div>}
    {loading ? <DashboardSkeleton /> : data && <>
      <section id="overview" className="analytics-grid four"><Metric icon={<StoreIcon />} label="Active stores" value={data.analytics?.activeStores || 0} note="Live now" /><Metric icon={<Eye />} label="Lifetime store visitors" value={data.analytics?.visitors || 0} note={`+${data.analytics?.visitorsToday || 0} Today`} /><Metric icon={<MessageCircle />} label="Confirmed orders" value={data.analytics?.orders || 0} note={`+${data.analytics?.ordersToday || 0} Today`} /><Metric icon={<Package />} label="Products live" value={data.analytics?.products || 0} note="Across all stores" /></section>
      <section id="applications" className="dash-section"><div className="dash-section-head"><div><span className="eyebrow">Fresh leads</span><h2>StoYangu applications</h2></div><span className="count-badge">{data.applications?.length || 0} total</span></div><div className="application-list">{data.applications?.map((application) => <article key={application.id}><span className={`status-dot ${application.status}`} /><div className="application-person">{(() => { const [personName, tiktokHandle] = application.name.split(' · TikTok: @'); return <><strong>{personName}</strong><a href={`tel:${application.phone}`}>{application.phone}</a>{tiktokHandle && <a className="application-tiktok" href={`https://tiktok.com/@${encodeURIComponent(tiktokHandle)}`} target="_blank" rel="noreferrer">@{tiktokHandle} on TikTok</a>}</>; })()}</div><span className="application-date">{new Date(application.created_at).toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })}</span><select value={application.status} onChange={(event) => applicationStatus(application, event.target.value as Application['status'])} aria-label={`Status for ${application.name}`}><option value="new">New</option><option value="contacted">Contacted</option><option value="approved">Approved</option><option value="closed">Closed</option></select></article>)}</div></section>
      <section id="stores" className="dash-section"><div className="dash-section-head stores-head"><div><span className="eyebrow">The network</span><h2>All stores</h2></div><label className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search stores or WhatsApp" /></label></div><div className="store-admin-grid">{stores.map((store) => { const billing = daysLeft(store); const installation = (data as any).installations?.[store.id]; return <article className="store-admin-card" key={store.id}><div className="store-card-top"><div className="store-avatar">{store.logo_url ? <img src={store.logo_url} alt="" /> : <span>{store.name[0]}</span>}</div><div><h3>{store.name}</h3><a href={storeLink(store.slug)} target="_blank" rel="noreferrer">{storeDomain(store.slug)} <ExternalLink /></a><span className={`install-status ${installation?.notifications_enabled ? 'ready' : ''}`}>{installation?.notifications_enabled ? 'App + alerts ready' : installation?.installed ? 'App installed · alerts off' : 'App not installed'}</span></div><div className="billing-control"><button className={`power-toggle ${store.is_active ? 'on' : ''}`} onClick={() => toggle(store)} aria-label={`Turn ${store.name} ${store.is_active ? 'off' : 'on'}`}><Power /><span>{store.is_active ? 'ON' : 'OFF'}</span></button><small className={billing.tone}>{billing.label}</small></div></div><div className="store-stats"><div><strong>{store.visitor_total.toLocaleString()}</strong><span>Visits <small>+{store.visitor_today} today</small></span></div><div><strong>{store.orders_total.toLocaleString()}</strong><span>WhatsApp <small>+{store.orders_today} today</small></span></div><div><strong>{(data as any).productCounts?.[store.id] || 0}</strong><span>Products live</span></div></div><div className="store-card-actions"><Link className="manage-button" to={`/manage/${store.id}`}>Manage store <ChevronRight /></Link><button className="json-button-admin details-button" onClick={() => setEditStore(store)} aria-label={`Edit ${store.name} details`}><Settings2 /></button><button className="json-button-admin" onClick={() => setJsonStore(store)} aria-label={`Edit ${store.name} HTML storefront`} title="Paste storefront HTML"><FileCode2 /> H</button><button className="json-button-admin" onClick={() => openArchives(store)} aria-label={`View archived orders for ${store.name}`} title="View archived orders"><Package /></button><button className="json-button-admin delete-store-button" onClick={() => setDeletingStore(store)} aria-label={`Delete ${store.name} completely`}><Trash2 /></button></div></article>; })}</div></section>
    </>}
  </main>{newStore && <NewStoreModal onClose={() => setNewStore(false)} onSaved={async () => { setNewStore(false); await load(); }} />}{editStore && <EditStoreModal store={editStore} onClose={() => setEditStore(null)} onSaved={async () => { setEditStore(null); await load(); }} />}{jsonStore && <HtmlEditor store={jsonStore} onClose={() => setJsonStore(null)} onSaved={async () => { setJsonStore(null); await load(); }} />}{notifications && <NotificationReview stores={data?.stores || []} onClose={() => setNotifications(false)} />}{deletingStore && <DeleteStoreModal store={deletingStore} onClose={() => setDeletingStore(null)} onSaved={async () => { setDeletingStore(null); await load(); }} />}{archiveView && <Modal title={`Archived orders: ${archiveView.store.name}`} onClose={() => setArchiveView(null)} wide>{archiveView.archives.length ? <div className="archive-list">{archiveView.archives.map((archive) => <article className="archive-entry" key={archive.id}><div><strong>{archive.order_count} orders</strong><small>Archived {new Date(archive.archived_at).toLocaleString('en-KE', { day: 'numeric', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit' })}</small></div><button className="secondary-button" onClick={() => downloadArchivedOrders(archiveView.store, archive.orders)}><Download /> Download CSV</button><details className="archive-details"><summary>View orders</summary><div className="archive-orders">{archive.orders.map((order, index) => <div className="archive-order" key={index}><strong>{String(order.product_name)}</strong><span>{String(order.customer_phone)} · {String(order.color || '—')} · {String(order.size || '—')} · {String(order.fulfilment || '')}</span><small>{String(order.status)} · {new Date(String(order.created_at)).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' })}</small></div>)}</div></details></article>)}</div> : <p className="archive-empty">No archived orders for this store yet. Orders are archived here automatically when the store is turned off.</p>}</Modal>}</div>;
}

function Metric({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: number; note: string }) { return <article className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{note}</small></article>; }
function DashboardSkeleton() { return <div className="dashboard-skeleton"><div /><div /><div /><div /><span /><span /></div>; }

function NewStoreModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ name: '', owner_password: '', whatsapp: '+254', categories: '', storefront_html: '' });
  const [logo, setLogo] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [htmlNote, setHtmlNote] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError('');
    if (!form.name.trim()) return setError('Store name is required.');
    if (!/^\+?[0-9\s-]{10,18}$/.test(form.whatsapp)) return setError('Add a valid owner WhatsApp number, including the country code.');
    if (form.owner_password.length < 8) return setError('Temporary password must be at least 8 characters.');
    setBusy(true); try {
      let logo_url = '';
      if (logo) logo_url = (await uploadImage(logo, 'logos')).url;
      const created = await apiFetch<{ id: number }>('/api/stores', { method: 'POST', body: JSON.stringify({ name: form.name, owner_password: form.owner_password, whatsapp: form.whatsapp, logo_url, categories: form.categories.split(',').map((item) => item.trim()).filter(Boolean), design_json: form.storefront_html.trim() ? { storefront_html: form.storefront_html } : {} }) });
      if (form.storefront_html.trim()) {
        setHtmlNote('Store created — saving HTML and copying photos…');
        try {
          await apiFetch('/api/storefront?action=save', { method: 'POST', body: JSON.stringify({ store_id: created.id, template: form.storefront_html }) });
        } catch (htmlErr) {
          console.warn('HTML save failed:', htmlErr);
          setError(`Store created — but the HTML save failed: ${htmlErr instanceof Error ? htmlErr.message : 'open the H button and try again'}`);
        }
      }
      onSaved();
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not create store.'); } finally { setBusy(false); }
  };
  return <Modal title="Create a new store" onClose={onClose} wide><form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Store name<input value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Lily" /><small>Subdomain preview: {storeDomain(form.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'store')}</small></label><label>Owner WhatsApp number<input type="tel" value={form.whatsapp} onChange={(event) => update('whatsapp', event.target.value)} placeholder="+254 7..." /><small>This is the owner's login name and order number.</small></label><label>Temporary password<div className="password-field"><input type={showPassword ? 'text' : 'password'} value={form.owner_password} onChange={(event) => update('owner_password', event.target.value)} placeholder="At least 8 characters" /><button type="button" onClick={() => setShowPassword((show) => !show)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label><label className="span-two">Product categories<input value={form.categories} onChange={(event) => update('categories', event.target.value)} placeholder="Fashion, Shoes, Accessories" /><small>Separate each category with a comma.</small></label><label className="upload-label span-two"><span>Store logo</span><input type="file" accept="image/*,.avif,.heic,.heif" onChange={(event) => setLogo(event.target.files?.[0] || null)} /><div><Box /> {logo ? logo.name : 'Choose from device or gallery'}</div></label>{htmlNote && <div className="form-success">{htmlNote}</div>}<label className="span-two html-paste-label">Storefront HTML from your AI (optional — you can also add it later with the H button)<textarea className="code-input" rows={8} value={form.storefront_html} onChange={(event) => update('storefront_html', event.target.value)} spellCheck={false} placeholder="<!doctype html>… paste the full HTML file here" /><small>Unsplash photos are copied into StoYangu storage automatically when you save.</small></label></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="button-primary" disabled={busy}>{busy ? 'Building store…' : 'Create store and owner login'} <Plus /></button></div></form></Modal>;
}

function EditStoreModal({ store, onClose, onSaved }: { store: Store; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ name: store.name, whatsapp: store.whatsapp, categories: (store.categories || []).join(', '), owner_password: '' });
  const [logo, setLogo] = useState<File | null>(null); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (form.name.trim().length < 2) return setError('Add a valid store name.'); if (!/^\+?[0-9\s-]{10,18}$/.test(form.whatsapp)) return setError('Add a valid WhatsApp number.'); if (form.owner_password && form.owner_password.length < 8) return setError('A new password must be at least 8 characters.'); setBusy(true); try { let logo_url = store.logo_url; if (logo) logo_url = (await uploadImage(logo, 'logos')).url; await apiFetch('/api/stores', { method: 'PUT', body: JSON.stringify({ action: 'details', id: store.id, name: form.name, whatsapp: form.whatsapp, owner_password: form.owner_password, logo_url, categories: form.categories.split(',').map((item) => item.trim()).filter(Boolean) }) }); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update the store.'); } finally { setBusy(false); } };
  return <Modal title={`Edit store details: ${store.name}`} onClose={onClose} wide><form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Store name<input value={form.name} onChange={(event) => update('name', event.target.value)} /><small>Changing the name also updates the store subdomain. The old link remains supported.</small></label><label>Owner WhatsApp number<input type="tel" value={form.whatsapp} onChange={(event) => update('whatsapp', event.target.value)} /><small>This is used for owner login and customer orders.</small></label><label className="span-two">Product categories<input value={form.categories} onChange={(event) => update('categories', event.target.value)} placeholder="Jerseys, Hoodies, Perfumes" /></label><label className="upload-label span-two"><span>Store logo</span><input type="file" accept="image/*,.avif,.heic,.heif" onChange={(event) => setLogo(event.target.files?.[0] || null)} /><div><Box /> {logo ? logo.name : store.logo_url ? 'Keep current logo or choose a replacement' : 'Choose a logo'}</div></label><label className="span-two">Reset owner password, optional<div className="password-field"><input type={showPassword ? 'text' : 'password'} value={form.owner_password} onChange={(event) => update('owner_password', event.target.value)} placeholder="Leave blank to keep the current password" /><button type="button" onClick={() => setShowPassword((show) => !show)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="button-primary" disabled={busy}>{busy ? 'Saving changes…' : 'Save store details'} <Check /></button></div></form></Modal>;
}

function DeleteStoreModal({ store, onClose, onSaved }: { store: Store; onClose: () => void; onSaved: () => void }) {
  const [confirmName, setConfirmName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const matches = confirmName.trim().toLowerCase() === store.name.trim().toLowerCase();
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError('');
    if (!matches) return setError(`Type ${store.name} exactly as shown to confirm the delete.`);
    setBusy(true);
    try {
      await apiFetch('/api/stores', { method: 'DELETE', body: JSON.stringify({ id: store.id }) });
      onSaved();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not delete the store.');
      setBusy(false);
    }
  };
  return <Modal title={`Delete store: ${store.name}`} onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="delete-warning"><Trash2 /><div><strong>This deletes everything about the store, forever.</strong><p>All products, photos, stats, the owner's login and the store itself will be removed. The subdomain <b>{storeDomain(store.slug)}</b> immediately becomes free, so you can create a brand-new store on that exact address. This cannot be undone.</p></div></div><label>Type <b>{store.name}</b> to confirm<input value={confirmName} onChange={(event) => setConfirmName(event.target.value)} placeholder={store.name} autoFocus /></label>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Keep store</button><button className="button-primary danger-primary" disabled={busy || !matches}>{busy ? 'Deleting store…' : 'Delete store forever'} <Trash2 /></button></div></form></Modal>;
}

function NotificationReview({ stores, onClose }: { stores: Store[]; onClose: () => void }) {
  const [batchKey, setBatchKey] = useState(''); const [combined, setCombined] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [customTitle, setCustomTitle] = useState(''); const [customBody, setCustomBody] = useState(''); const [selectedStores, setSelectedStores] = useState<number[]>([]); const [sendAll, setSendAll] = useState(true); const [customBusy, setCustomBusy] = useState(false);
  const generate = async () => { setBusy(true); setMessage(''); try { const result = await apiFetch<{ batchKey: string; combinedText: string }>('/api/notifications?action=generate'); setBatchKey(result.batchKey); setCombined(result.combinedText); } catch (err) { setMessage(err instanceof Error ? err.message : 'Could not generate review.'); } finally { setBusy(false); } };
  useEffect(() => { generate(); }, []);
  const copy = async () => { await navigator.clipboard.writeText(combined); setMessage('Combined list copied.'); };
  const confirm = async () => { if (!batchKey) return; setBusy(true); try { const result = await apiFetch<{ scheduled: boolean; scheduledFor: string }>('/api/notifications', { method: 'POST', body: JSON.stringify({ batchKey, combinedText: combined }) }); setMessage(`Confirmed. These are scheduled for ${new Date(result.scheduledFor).toLocaleString('en-KE', { timeZone: 'Africa/Nairobi', weekday: 'short', day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' })}. Nothing was sent immediately.`); } catch (err) { setMessage(err instanceof Error ? err.message : 'Could not schedule notifications.'); } finally { setBusy(false); } };
  const sendCustom = async () => { if (!customTitle.trim() || !customBody.trim()) return setMessage('Add a custom notification title and message.'); if (!sendAll && !selectedStores.length) return setMessage('Choose at least one store account.'); setCustomBusy(true); try { const result = await apiFetch<{ sent: number; failed: number; installedRecipients: number }>('/api/custom-notifications', { method: 'POST', body: JSON.stringify({ title: customTitle, body: customBody, store_ids: sendAll ? [] : selectedStores }) }); setMessage(`Custom notification sent to ${result.sent} installed device${result.sent === 1 ? '' : 's'}${result.failed ? `; ${result.failed} failed` : ''}.`); setCustomTitle(''); setCustomBody(''); } catch (err) { setMessage(err instanceof Error ? err.message : 'Could not send custom notification.'); } finally { setCustomBusy(false); } };
  return <Modal title="Notification centre" onClose={onClose} wide><div className="review-toolbar"><p><b>Daily review:</b> edit at 7 PM, then confirm. Confirmed messages wait and send at exactly <b>7:30 PM Kenya time</b>.</p><button className="secondary-button" onClick={copy} disabled={!combined}><Clipboard /> Copy all</button></div>{busy && !combined ? <div className="review-loading"><RefreshCw className="spin" /> Building each store summary…</div> : <textarea className="notification-editor" value={combined} onChange={(event) => setCombined(event.target.value)} spellCheck={false} />}{message && <div className={message.includes('Confirmed') || message.includes('sent') || message.includes('copied') ? 'form-success' : 'form-error'}>{message}</div>}<div className="modal-actions"><button className="secondary-button" onClick={generate} disabled={busy}><RefreshCw /> Regenerate</button><button className="button-primary" onClick={confirm} disabled={busy || !combined}><CalendarClock /> Confirm for 7:30 PM</button></div><section className="custom-push-box"><span className="eyebrow">Send a separate message</span><h3>Custom app notification</h3><p>Send a short update to every installed owner or only the accounts you choose.</p><div className="form-grid"><label>Notification title<input value={customTitle} maxLength={80} onChange={(event) => setCustomTitle(event.target.value)} placeholder="e.g. New product tip" /></label><label className="span-two">Message<textarea rows={4} maxLength={800} value={customBody} onChange={(event) => setCustomBody(event.target.value)} placeholder="Write the message owners should receive…" /></label></div><div className="recipient-choice"><button className={sendAll ? 'active' : ''} onClick={() => setSendAll(true)}>All installed owners</button><button className={!sendAll ? 'active' : ''} onClick={() => setSendAll(false)}>Choose accounts</button></div>{!sendAll && <div className="store-recipient-grid">{stores.map((store) => <label key={store.id}><input type="checkbox" checked={selectedStores.includes(store.id)} onChange={() => setSelectedStores((current) => current.includes(store.id) ? current.filter((id) => id !== store.id) : [...current, store.id])} /><span><strong>{store.name}</strong><small>{store.owner_name}</small></span></label>)}</div>}<button className="button-primary custom-send" onClick={sendCustom} disabled={customBusy}>{customBusy ? 'Sending…' : <><Send /> Send custom notification</>}</button></section></Modal>;
}
